### ISSUE TITLE
The replay file saved from online replay is broken

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#25]

**Comment by Deardrops** [comment]
add  `game.io.datas = content.messagePacks` 
after https://github.com/webxoss/webxoss-client/blob/81a74dfdc89c98ce632dcbdabc1a5ddbc77f9123/RoomManager.js#L981

**Comment by webxoss** [comment]
惨不忍睹的代码。。。。提个pr吧。。。
