### ISSUE TITLE
WD18

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#33]
@Deardrops 
我写了几张WD17了，你来帮忙写WD18吧。
WD17-WD18分支
中文名字不管，中文效果自己随便翻吧，自己翻有利于写效果。
英文名字和效果抄这里 http://selector-wixoss.wikia.com/wiki/WXD-18_Green_Berserk
效果模板复制粘贴这里 https://gist.github.com/webxoss/90e992ad0cc645e0214cbab8d0e7f23d
写就好，不用实现，比如现在没有「获得硬币」，你就假装有这么个方法直接调用就好。

注意代码风格不一样，只能用ES5，tab缩进，逗号后面不空格

注意点：

- [ ] WD17-006 FAQ2

**Comment by Deardrops** [comment]
收到
