### ISSUE TITLE
Wrong touch area on Mobile Chrome

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#44]
Easel.js gets wrong touch area on Mobile Chrome when zooming.

**Comment by Deardrops** [comment]
[Easel.js #598](https://github.com/CreateJS/EaselJS/issues/598#issuecomment-176299538) 中一条评论指出了问题所在：`Stage.js`中的`_getElemntRect()`函数。完整代码请见[这里](https://github.com/CreateJS/EaselJS/blob/49d20661bd989405f82f69683fd641cf50b8b9f5/src/easeljs/display/Stage.js#L570)。
```
p._getElementRect = function(e) {
    var bounds;
    try { bounds = e.getBoundingClientRect(); } // this can fail on disconnected DOM elements in IE9
    catch (err) { bounds = {top: e.offsetTop, left: e.offsetLeft, width:e.offsetWidth, height:e.offsetHeight}; }

    var offX = (window.pageXOffset || document.scrollLeft || 0) - (document.clientLeft || document.body.clientLeft || 0);
    var offY = (window.pageYOffset || document.scrollTop || 0) - (document.clientTop  || document.body.clientTop  || 0);

    // 省略了计算padding的代码
    // note: in some browsers bounds properties are read only.
    return {
        left: bounds.left+offX+padL,
        right: bounds.right+offX-padR,
        top: bounds.top+offY+padT,
        bottom: bounds.bottom+offY-padB
    }
```
简单说结论吧，为了在缩放后的视图中计算并返回正确的位置：
- 桌面视图中，需要加上`offX/offY`的值。
- 手机视图中，则**不需要加上`offX/offY`的值。**

具体原因我查阅了很多资料也没有弄清。
经过测试，以下的修复方式是可行的：

*判断是否为手机设备，如果是则将`offX`和`offY`的值设置为0。*

PS：ios设备上没有测试过。

**Comment by webxoss** [comment]
不错。但是 iOS 现在是正确的，改了 iOS 就不对了吧？
应该是 chrome 的 bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=496285

**Comment by Deardrops** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=489206
帖子最后提到这个bug将会在chrome 61修复。
通用的解决方法是在 `flags` 中 enable `inert-visaul-viewport` 特性。

`chrome://flags#inert-visual-viewport`

所以我们要做出修复么？

**Comment by webxoss** [comment]
写脏代码，检测 61 以下的手机 chrome
