### ISSUE TITLE
wx16 cards issue fallback - red card part

### ISSUE THREAD

**Issue by Deardrops** [webxoss/webxoss-core#54]
wx16中 所有红色卡已经测试过，反馈问题如下：
- [x] WX16-027 这张卡的效果应该是：`将两个格子中的signi放在一起，这张卡放在上面，再将他们放在2个格子中的其中一个`
> http://www.takaratomy.co.jp/products/wixoss/card/card_detail.php?card_no=WX16-027
Q:《十字の炎槍　サナユキ》の[ライズ]はどのようにしたらいいですか？
A:《十字の炎槍　サナユキ》はあなたの場に＜武勇＞のシグニが2体あるときに出すことができます。どちらかのシグニゾーンに2体を重ね、その上に《十字の炎槍　サナユキ》を重ねて出します。
- [x] PR-328 效果2 不能发动
- [x] WX16-057 查看我方卡组顶三张牌时，只查看了三张牌的背面...
- [x] WX16-037 查看我方卡牌顶四张牌时，有可能只看到背面...
  - 这两个问题都会在首次发动该效果时出现，后面发动是正常的
![image](https://user-images.githubusercontent.com/9463871/29003298-b286839e-7ae6-11e7-9e16-2e4214358e0e.png)

**Comment by webxoss** [comment]
除了第一个都改了
第一个比较麻烦

**Comment by webxoss** [comment]
都改了，回归测试一下，没问题就吧这个 issue close 掉

**Comment by Deardrops** [comment]
- [x] wx16-039 当`wx16-027`升阶时，若选择的召唤的区域不在此牌的上方，不会发动此牌的效果

**Comment by Deardrops** [comment]
- [x] wx16-038 【自】效果1 在查看卡组顶一张卡为`不持有<升阶>的<武勇>`后，无法将其召唤

**Comment by webxoss** [comment]
看成持有了，已改。
