### ISSUE TITLE
WX13 Test

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#9]
- [x] 1774 WX13-001 真·游月·伍
- [x] 1775 WX13-002 救済の冥者　ハナレ
- [x] 1776 WX13-003 アイスフレイム・シュート
- [x] 1777 WX13-004 枯樹生華
- [x] 1769 WX13-005A 白羅星　フルムーン
- [x] 1768 WX13-005B 白羅星　ニュームーン
- [x] 1778 WX13-006A 黒幻蟲　オウグソク【ＦＡ】
- [x] 1779 WX13-006B 黒幻蟲　オウグソク【ＨＳ】
- [x] 1767 WX13-007 博愛の使者　サシェ・リュンヌ
- [x] 1780 WX13-008 星占の巫女　リメンバ・トワイライト
- [x] 1781 WX13-009 博愛の使者　サシェ・カルティエ
- [x] 1782 WX13-010 ゼノエントランス
- [x] 1783 WX13-011 遊月・純肆
- [x] 1784 WX13-012 立炎交差
- [x] 1785 WX13-013 三焼揃踏
- [x] 1786 WX13-014 エルドラ×マークⅣＰＬＵＳ
- [x] 1787 WX13-015 アンダー・ワン
- [x] 1788 WX13-016 青幻水　リヴァイア
- [x] 1789 WX13-017 アイヤイ★コール
- [x] 1790 WX13-018 意気軒昂
- [x] 1791 WX13-019 緑弐ノ遊　スイングライド
- [x] 1792 WX13-020 懇願の冥者　ハナレ
- [x] 1793 WX13-021 傀儡の冥者　ハナレ
- [x] 1794 WX13-022 来夢の冥者　ハナレ
- [x] 1795 WX13-023 ミュウ＝モルト
- [x] 1796 WX13-024 残悔の冥者　ハナレ
- [x] 1797 WX13-025 フォービドゥン・ゲーム
- [x] 1798 WX13-026 ネクスト・パニッシュ
- [x] 1799 WX13-027 サーバント・アライブ
- [x] 1800 WX13-028 カラーレス　サーバンツ
- [x] 1801 WX13-029 羅星宙姫　ノーザンセブン
- [x] 1802 WX13-030 幻竜神姫　バハムート
- [x] 1803 WX13-031 弩中砲　グスタフト
- [x] 1766 WX13-032 幻深水姫　デメニギス
- [x] 1804 WX13-033 ＭＩＲＲＯＲ
- [x] 1805 WX13-034 幻獣神　マンモ
- [x] 1806 WX13-035 参ノ遊　ゴガツドール
- [x] 1807 WX13-036 フィア＝パトラ
- [x] 1808 WX13-037 幻蟲　スカラベ
- [x] 1765 WX13-038 千夜の夜王　イフリード
- [x] 1809 WX13-039 羅星　ホロスコープ
- [x] 1810 WX13-040 思索の体現　_シンカー_
- [x] 1811 WX13-041 巨弓　ガンデヴァ
- [x] 1812 WX13-042 コードメイズ　コロッセオ
- [x] 1813 WX13-043 弩砲　トミガン
- [x] 1764 WX13-044 羅石　ビスマス
- [x] 1814 WX13-045 轟左砲　ドーラ
- [x] 1815 WX13-046 轟右砲　ドスラフ
- [x] 1816 WX13-047 同砲の紲絆
- [x] 1817 WX13-048 幻水　テッポウオ
- [x] 1818 WX13-049 羅原　Ｌｉ
- [x] 1819 WX13-050 ＶＯＩＣＥ　ＣＨＡＮＧＥ
- [x] 1763 WX13-051 幻竜　＃モリドラ＃
- [x] 1820 WX13-052 参ノ遊　コイノボリ
- [x] 1821 WX13-053 幻獣　ホトトギ
- [x] 1822 WX13-054 弐ノ遊　フキナガシ
- [x] 1823 WX13-055 千夜の四夜　ソロモン
- [x] 1824 WX13-056 フィア＝ネロザラン
- [x] 1825 WX13-057 幻蟲　オニヤンマ
- [x] 1826 WX13-058 ドライ＝ダイオ娘
- [x] 1827 WX13-059 ドライ＝アグリピナ
- [x] 1828 WX13-060 ストレンジ・カインド
- [x] 1829 WX13-061 羅星　カプスフォー
- [x] 1830 WX13-062 巨弓　ハラダヌ
- [x] 1831 WX13-063 羅星　カプススリー
- [x] 1832 WX13-064 羅星　カプスツー
- [x] 1833 WX13-065 恵の梅雨　マルティエル
- [x] 1834 WX13-066 羅星　カプスワン
- [x] 1835 WX13-067 羅石　ティンオ
- [x] 1836 WX13-068 爆砲　ファイバル
- [x] 1837 WX13-069 爆砲　フウバ
- [x] 1838 WX13-070 羅石　アンチモン
- [x] 1839 WX13-071 羅石　モナズ
- [x] 1840 WX13-072 幻水　イダビウオ
- [x] 1841 WX13-073 幻水　ホンビウオ
- [x] 1842 WX13-074 コードアート　Ｂ・Ｒ・Ｄ
- [x] 1843 WX13-075 幻水　タチウオ
- [x] 1844 WX13-076 コードアート　Ｂ・Ｅ・Ｃ
- [x] 1845 WX13-077 幻獣　ユリカモメ
- [x] 1846 WX13-078 幻竜　＃エリマキ＃
- [x] 1847 WX13-079 幻獣　ウグイス
- [x] 1848 WX13-080 幻竜　＃アゴヒゲ＃
- [x] 1849 WX13-081 弐ノ遊　カザグルマ
- [x] 1850 WX13-082 壱ノ遊　カミカブト
- [x] 1851 WX13-083 幻獣　メジロ
- [x] 1852 WX13-084 幻竜　＃キノボリ＃
- [x] 1853 WX13-085 フィア＝カリ
- [x] 1854 WX13-086 幻蟲　ギンヤンマ
- [x] 1855 WX13-087 ドライ＝クロホ
- [x] 1856 WX13-088 千夜の三夜　マリード
- [x] 1857 WX13-089 幻蟲　アカトンボ
- [x] 1858 WX13-090 千夜の二夜　シャイターン
- [x] 1859 WX13-091 ツヴァイ＝ゾヒ
- [x] 1860 WX13-092 ツヴァイ＝チェボル
- [x] 1861 WX13-093 幻蟲　ヤゴ
- [x] 1862 WX13-094 アイン＝ニネトキリ
- [x] 1863 WX13-095 アイン＝ルクボル
- [x] 1864 WX13-096 千夜の一夜　ジン
- [x] 233 WX13-097 サーバント　Ｑ２
- [x] 234 WX13-098 サーバント　Ｔ２
- [x] 235 WX13-099 サーバント　Ｄ２
- [x] 236 WX13-100 サーバント　Ｏ２
- [x] PR-294
- [x] PR-293
- [x] PR-292
- [x] PR-291
- [x] PR-290
- [x] PR-289
- [x] PR-288

**Comment by gugugupan** [comment]
PR-266 罗星 毕宿五：结束阶段废弃后，禁止对面攻击的效果可以无限次发动（应该只能发动一次）

# 

Fixed. 不知道修对了没，麻烦再测一次噢。 (同一个bug就直接修改好了)

# 

Fixed.

**Comment by gugugupan** [comment]
WX13-005B 白罗星新月：
（1）名字写错；
（2）在以魔法切入出场时，服务器出错

```
ReferenceError: effects is not defined
    return this.player.selectAsyn('CHOOSE_EFFECT', effects).callback(this, function (e...
@CardInfo.js (Line 107324, Row 5)
```

（上面这段是手打的，只截了图忘记复制内容了）

# 

Fixed. Re-test required.

# 

Fixed.

**Comment by gugugupan** [comment]
WX13-005A 白羅星 满月
1. 【常】效果是“其他共鸣精灵不受对手SIGNI效果影响”，现在自己本身也不会受到对手效果影响；
2. 【出】效果并没有正确生效，对手探查四+木星的组合，木星成功踢出第二脚。

# 

Fixed. Confirmation required.

# 

WX13-029 羅星宙姫 北斗七星
启动（1）效果时出错:
TypeError: target.player is undefined (@Mask.js (第 48 行，第 17 列))
if (!reset && inArr(this.prop,Card.abilityProps) && (target.canNotGainAbility ||...
（2）效果正确
（3）效果正确
（4）效果正确
不过每次效果启动完毕之后，对手在战阶只能使用一次技艺，使用不出来第二次技艺效果，不知道是不是一个BUG。

# 

(1) Fixed. Confirmation required.
"战阶只能使用一次技艺"可能由别的操作引起？没看到相关的代码。

@gugugupan

**Comment by sssuwako** [comment]
WX13-031弩中炮 古斯塔夫  WX13-045轰左炮 朵拉  WX13-046轰右炮 朵丝拉夫
cross条件判定等存在问题
应该是左右、左中右，这两中情况算达成cross

# 

Fixed. 请确认。

**Comment by webxoss** [comment]
ALL DONE!
